### ISSUE TITLE
Cannot download, must be smaller than 20480 bytes

### ISSUE THREAD

**Issue by firelad97** [icflorescu/openshift-cartridge-nodejs#1]
Tried creating an app with this cartridge but the result was download failed due to size.

**Comment by icflorescu** [comment]
The cartridge **is** way smaller than 20 MB and it **does** work.
Maybe you're getting the error message because you're trying to use the URL `https://github.com/icflorescu/openshift-cartridge-nodejs` instead of
`http://cartreflect-claytondev.rhcloud.com/github/icflorescu/openshift-cartridge-nodejs`?

If that's the case, it's a common pitfall for people trying to deploy custom cartridges on OpenShift for the first time. I'll make sure to put this in an FAQ section in the README...

**Comment by firelad97** [comment]
Ah! My bad, I thought I need to use Github link.

**Comment by icflorescu** [comment]
No problem. IT happened to me too.
