### ISSUE TITLE
node_modules are not required

### ISSUE THREAD

**Issue by Myshkouski** [icflorescu/openshift-cartridge-nodejs#47]
I'm trying to start the simplest HelloWorld application using the cartridge.
Here is the app-root:

```
app-root
    node_modules
        mod
            index.js
    index.js
```

index.js:

```
var mod = require("mod")
console.log(mod)
```

node_modules/mod/index.js:

```
module.exports = "hello world!"
```

After pushing it to Openshift get an error:

> ==> app-root/logs/nodejs.log <==
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/var/lib/openshift/5761644a0c1e66259f0001da/app-root/runtime/repo/index.js:1:73)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Function.Module.runMain (module.js:447:10)

Using `ls`via `ssh`shows there is nothing in `/var/lib/openshift/5761644a0c1e66259f0001da/app-root/runtime/repo/node_modules`.
Please, explain me what's wrong as I'm a node.js begginner.
Highly appreciate your help.

**Comment by icflorescu** [comment]
I assume you know that `node_modules` is managed by `npm`, and usually `.gitignore`d?

Even if you didn't add it to `.gitignore`, the `npm`s that are not specified in `package.json` `dependencies` are pruned automatically when you deploy your app to OpenShift (see the `build()` function in the cartridge [control script](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/bin/control)).

As a well-known common practice, you should avoid **manually** placing modules in `node_modules`.

Change your structure to something like:

```
app-root
  mod
    index.js
  index.js
```

Then, in `app-root/index.js`:

```
var mod = require('./mod');
console.log(mod);
```

Please note that this issue is **not** cartridge-related. How the module system works is rather common development knowledge and one of the things you should learn first when you start with Node.js – the [official documentation](https://nodejs.org/api/modules.html) is a good place to start, there are also lots of good books available.
