### ISSUE TITLE
Version is not changing

### ISSUE THREAD

**Issue by rohitketkar87** [icflorescu/openshift-cartridge-nodejs#51]
I have created new application in openshift using Node.js Auto-Updating cartridge. After application is created its showing node version 5.11.1. However I want node version 5.0.0. I have made the necessary changes in .openshift/NODE_VERSION_URL. But still i see version 5.0.0 installed. 
Have I done anything wrong or I forgot to do something. PFA screenshots.
![node_version2](https://cloud.githubusercontent.com/assets/20128493/16341086/fc19974c-3a48-11e6-88ef-62d85e6f62f7.PNG)
![node_version1](https://cloud.githubusercontent.com/assets/20128493/16341087/fc1b8c64-3a48-11e6-81d2-5c8a5929236d.PNG)

**Comment by drakewashere** [comment]
> After application is created its showing node version 5.11.1. However I want node version 5.0.0. [...] But still i see version 5.0.0 installed. 

Wouldn't this indicate that it installed the correct version?

**Comment by icflorescu** [comment]
You're asking for `5.0.0` and you're getting `5.0.0`. How is this wrong?

Please follow up with more info or close the (non-)issue :-)

**Comment by rohitketkar87** [comment]
Hi,
I want specific version of node which is 5.0.0 but by default installed
version is 5.11.1

You're asking for 5.0.0 and you're getting 5.0.0. How is this wrong?

Please follow up with more info or close the (non-)issue :-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/icflorescu/openshift-cartridge-nodejs/issues/51#issuecomment-228470422,
or mute the thread
https://github.com/notifications/unsubscribe/ATMi7aTki8ts-9rU3rLdd5QwxviP3Uxqks5qPFDhgaJpZM4I91r7
.

**Comment by drakewashere** [comment]
> I want specific version of node which is 5.0.0 but by default installed version is 5.11.1

If you want to change the default behaviour while still getting updates, you would probably be best off just making your own fork and merge changes from the original branch as needed.

**Comment by icflorescu** [comment]
**By default** you're getting the last stable Node.js version according to semver.io. If you're setting `.openshift/NODE_VERSION_URL` file marker or `NODE_VERSION_URL` env var to `5.0.0` **and do a git push**, `v5.0.0` will be installed.

Did you forget to `git push`?

You're still getting `5.1.1` after pushing?

As @drakecsmall noticed as well, your initial post implied you were getting the expected result:

> However I want node version 5.0.0. I have made the necessary changes in .openshift/NODE_VERSION_URL. But still i see version **5.0.0** installed.

**Comment by rohitketkar87** [comment]
Hi,
I didn't do git push. What I did is I directly created dir .openshift in
repo directory and set the marker NODE_VERSION_URL.  I didn't use git at
all.
I have seen the tutorial where we have to add github repo and do git push.
In that case while pushing I was getting permission denied error for git
push.
Can you please give me detailed steps again. Just to make sure I am not
doing anything wrong.

P.S - I have created the application using web comsole not from rhc client
tool.
On Jun 25, 2016 3:58 AM, "Ionut-Cristian Florescu" notifications@github.com
wrote:

_By default_ you're getting the last stable Node.js version according to
semver.io. If you're setting .openshift/NODE_VERSION_URL file marker or
NODE_VERSION_URL env var to 5.0.0 _and do a git push_, v5.0.0 will be
installed.

Did you forget to git push?

You're still getting 5.1.1 after pushing?

As @drakecsmall https://github.com/drakecsmall noticed as well, your
initial post implied you were getting the expected result:

However I want node version 5.0.0. I have made the necessary changes in
.openshift/NODE_VERSION_URL. But still i see version _5.0.0_ installed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/icflorescu/openshift-cartridge-nodejs/issues/51#issuecomment-228478066,
or mute the thread
https://github.com/notifications/unsubscribe/ATMi7duTuVrNI9JOjtXJWxSkDM29kGQSks5qPFoKgaJpZM4I91r7
.

**Comment by icflorescu** [comment]
How did you create the `.openshift` dir? Are you working through the SSH console and manually adding/changing the application source files?

In that case, I see where the problem is. The Node.js update function (residing in [`lib/util`](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/lib/util)) is triggered by the cartridge build event (see [`bin/control`](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/bin/control) for specifics). But since you're not using git and not doing a push, there's no way for the cartridge to "know" it has to update. There's no practical way of simply "watching" the `.openshift` folder or the environment variables.

The OpenShift application deployment mechanism has been designed to work around git. So what you should do is clone the application repository on your machine as shown in the OpenShift web console and deploy using git push and everything will work as expected. I'm sure there are also tutorials on their website somewhere on how to deploy with git.

I have no idea why you're getting a _permission denied_ error when trying to push; there are many possible causes: git might not be properly configured on your system, your might have forgotten to publish your SSH public key to your OpenShift account, etc...

But it looks like the issue is not specific to this cartridge.

**Comment by rohitketkar87** [comment]
@icflorescu @drakecsmall Issue is resolved. Thanks a lot. I reconfigured GIT again and pushed the repo to openshift. Working as expected. :) :+1:
